<template>
    <div class="section-1" :style="{ backgroundImage: backgroundImg }">
        <div class="overlay"></div>
        <div class="a">Beliefs</div>
        <span style="color: white; padding-bottom: 5rem; z-index: 2;">Our Beliefs & Principles</span>
    </div>
    <div class="section-2">
        <div class="b-container">
            <div class="head" style="background-color: aliceblue">God</div>
            <div class="details">There is one God, Creator of all things, infinitely perfect, and eternally existing in three manifestations: Father, Son and Holy Spirit.</div>
        </div>
        <div class="b-container">
            <div class="head" style="background-color: #fff0f0">Jesus Christ</div>
            <div class="details">Jesus Christ is true God and true man, having been conceived of the Holy Spirit and born of the Virgin Mary. He died on the cross, the complete and final sacrifice for our sins according to the Scriptures. Further, He arose bodily from the dead, ascended into heaven, where, at the right hand of the Majesty on High, He is now our High Priest and Advocate.</div>
        </div>
        <div class="b-container">
            <div class="head" style="background-color: #f8f0ff">The Holy Spirit</div>
            <div class="details">The ministry of the Holy Spirit is to glorify the Lord Jesus Christ and during this age, to convict men of sin, regenerate the believing sinner, indwell, guide, instruct, and empower the believer for godly living and service. Man - Man was created in the image of God but fell into sin and is therefore lost, and only through regeneration by the Holy Spirit can salvation and spiritual life be obtained.</div>
        </div>
        <div class="b-container">
            <div class="head" style="background-color: #fff0f0">Salvation</div>
            <div class="details">The shed blood of Jesus Christ and His resurrection provide the only ground for justification and salvation for all who believe, and only such as receive Jesus Christ by faith are born of the Holy Spirit and thus become children of God. The Return of Jesus Christ - The personal, pre-millennial, and imminent return of our Lord Jesus Christ is our hope and has a vital bearing on the personal life and service of the believer.</div>
        </div>
        <div class="b-container">
            <div class="head" style="background-color: #f0fff1">Future Events</div>
            <div class="details">There will be a bodily resurrection of all the dead; of the believer to everlasting blessedness and joy with the Lord, and of the unbeliever to judgment and everlasting conscious punishment.</div>
        </div>
        <div class="b-container">
            <div class="head" style="background-color: #fffaf0">The Church</div>
            <div class="details">The true Church is composed of all such persons, who through saving faith in Jesus Christ, has been regenerated by the Holy Spirit and are united together in the body of Christ of which He is the head.</div>
        </div>
        <div class="b-container">
            <div class="head" style="background-color: aliceblue">Baptism and Communion</div>
            <div class="details">Water baptism by immersion soon after accepting Christ as personal Savior, is a testimony of death to sin and resurrection to a new life. The Lord's Supper is a memorial service setting forth in sacred and symbolic manner the death of the Lord Jesus Christ; all true believers and only believers should share in it.</div>
        </div>
    </div>
    <Footer />
</template>

<script setup>
    import Footer from '../layout/Footer.vue'
    import { ref, onMounted } from 'vue'
    import background from '../../assets/background_color.png'

    const backgroundImg = ref(`url(${background})`)

    onMounted(() => {
        for(let i = 0; i < 7; i++) {
            new IntersectionObserver(entries => {
                entries.forEach(entry => {
                    const t = entry.target;
                    var direction = "";
                    if(i % 2 == 0) {
                        direction = 'ease-left-animation';
                    } else {
                        direction = 'ease-right-animation';
                    }
                    
                    if (entry.isIntersecting) {
                        t.classList.add(direction);
                        return; // if we added the class, exit the function
                    }

                    // We're not intersecting, so remove the class!
                    t.classList.remove(direction);
                });
            }).observe(document.querySelectorAll(`.b-container`)[i]);
        }
    })
</script>

<style scoped>
    .section-1 {
        position: relative;
        display: flex;
        align-items: center;
        flex-direction: column;
        min-height: 15rem;
        background-repeat: no-repeat;
        background-size: cover;
        padding-top: 75px;
    }
    .section-2 {
        display: flex;
        flex-direction: row;
        flex-flow: wrap;
        padding: 4rem 0;
        align-items: center;
        justify-content: center;
    }

    .a {
        margin-top: 3rem;
        margin-bottom: 2rem;
        color: white;
        text-align: center;
        font-size: 2rem;
        font-weight: 600;
        letter-spacing: 0.25rem;
        position: relative;
        animation-name: fade-white;
        animation-timing-function: ease;
        animation-duration: 1s;
    }

    .b-container {
        width: 75vw;
        padding: 0.5rem;
        border-radius: 2px;
        color: #1b205d;
        margin-bottom: 2rem;
        position: relative;
    }

    .head {
        font-weight: 700;
        font-size: 2rem;
        background-color: #ffffff;
        padding: 1rem;
        background-color: aliceblue;
    }

    .details {
        padding: 1rem;
        line-height: 1.5rem;
    }

    .ease-left-animation {
        animation-name: ease-left;
        animation-timing-function: ease;
        animation-fill-mode: forwards;
        animation-duration: 1s;
    }

    .ease-right-animation {
        animation-name: ease-right;
        animation-timing-function: ease;
        animation-fill-mode: forwards;
        animation-duration: 1s;
    }

    @keyframes ease-left {
        from {opacity: 0; left: 3rem }
        to {opacity: 1; left: 0; }
    }

    @keyframes ease-right {
        from {opacity: 0; right: 3rem }
        to {opacity: 1; right: 0; }
    }

    @keyframes fade-white {
        from {color: transparent; top: 5vh }
        to {color: white; top: 0; }
    }

    .overlay {
        position: absolute;
        top: 0;
        width: 100%;
        height: 100%;
        opacity: 0.6;
        background-image: linear-gradient(#6b0e3a, #793354);
    }
</style>
